name: Selenium Tests Pipeline

on:
  push:
    branches: [main]

jobs:
  selenium_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Selenium WebDriver
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt-get -yqq update
        sudo apt-get -yqq install firefox
        python -m webdriver_manager.chrome --versions-path=/usr/bin
        python -m webdriver_manager.firefox --linkpath /usr/bin

    - name: Run Selenium tests
      run:  pytest -v -s ./test_snaptrude.py
      env:
        BROWSER: ${{ matrix.browser }}

    - name: Notify on Slack
      if: always()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: "#test-notifications"
        SLACK_USERNAME: "GitHub Actions"
        SLACK_MESSAGE: "Selenium tests are done!"
